name: coffee_beanventory
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.6.0
  flame_forge2d: ^0.12.5
  flutter:
    sdk: flutter
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/