name: coffee_beanventory
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.7.2
  flame_forge2d: ^0.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.1
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.2
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^6.5.6
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  intl: ^0.17.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  riverpod_annotation: ^2.0.1
  shared_preferences: ^2.1.1
  simple_logger: ^1.9.0+2
  sleek_circular_slider: ^2.0.1
  state_notifier: ^0.7.2+1
  test: ^1.24.3
  webview_flutter: ^4.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.1
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
